version: '3.3'
services:
  app:
    build: .
    ports:
      - 8080:8080

    depends_on:
      - sqlserverdb

  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1450:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: PassCode#2024